version: '3.8'

networks:
  db_network:
    driver: bridge

services:
  postgresdb:
    image: postgres:17
    container_name: postgresdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: psql_db
    ports:
      - "5432:5432"
    volumes:
      - "/home/nodetree/Music/db_config/pg_hba.conf:/etc/postgresql/postgresql.conf.d/pg_hba.conf"
      - "/home/nodetree/Music/db_config/postgres_data:/var/lib/postgresql/data"
    networks:
      - db_network
    entrypoint: >
      bash -c "docker-entrypoint.sh postgres && 
      sleep 10 && 
      psql -U admin -d psql_db -c \"GRANT ALL PRIVILEGES ON DATABASE psql_db TO admin;\""

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - "/home/nodetree/Music/db_config/mysql.conf:/etc/mysql/mysql.cnf"
      - "/home/nodetree/Music/db_config/mysql_data:/var/lib/mysql"
    networks:
      - db_network
    entrypoint: >
      bash -c "docker-entrypoint.sh mysqld && 
      sleep 10 && 
      mysql -u root -p$MYSQL_ROOT_PASSWORD -e \"GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';\" && 
      mysql -u root -p$MYSQL_ROOT_PASSWORD -e \"ALTER USER 'admin'@'%' IDENTIFIED BY 'admin123';\" && 
      mysql -u root -p$MYSQL_ROOT_PASSWORD -e \"FLUSH PRIVILEGES;\""

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    environment:
      CB_SERVER_HOST: 0.0.0.0
      CB_SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - db_network

volumes:
  postgres_data:
  mysql_data:
